Translations = {
    "RM_UI_Title", "Real Metabolism",
    "RM_UI_ToggleHint", "Press N to toggle the metabolism panel",
    "RM_UI_TabStatus", "Status",
    "RM_UI_TabTrend", "Trend",
    "RM_UI_TabHealth", "Health",
    "RM_Micro_sodium", "Sodium",
    "RM_Micro_potassium", "Potassium",
    "RM_Micro_calcium", "Calcium",
    "RM_Micro_iron", "Iron",
    "RM_Micro_vitA", "Vitamin A",
    "RM_Micro_vitC", "Vitamin C",
    "RM_Micro_vitD", "Vitamin D",
    "RM_Micro_vitB1", "Vitamin B1",
    "RM_UI_Hydration", "Hydration",
    "RM_UI_Energy", "Energy",
    "RM_UI_Load", "Today's Load",
    "RM_UI_Macros", "Macros",
    "RM_UI_Weight", "Weight",
    "RM_Tier_Danger", "Danger",
    "RM_Tier_Attention", "Low",
    "RM_Tier_Ok", "Adequate",
    "RM_Tier_Excess", "Excess",
    "RM_Hyd_Normal", "Hydrated",
    "RM_Hyd_Thirsty", "Thirsty",
    "RM_Hyd_Low", "Dehydrated",
    "RM_Hyd_Critical", "Severely dehydrated",
    "RM_Ef_Normal", "Energized",
    "RM_Ef_Low", "Low energy",
    "RM_Ef_Frozen", "Exhausted",
    "RM_UI_NoDisease", "No deficiency diseases",
    "RM_UI_Trend7", "Last 7 days",
    "RM_NeatUI_Missing", "NeatUI is missing. Please subscribe to NeatUI (Workshop 3508537032) to use Real Metabolism.",
}
