Translations = {
    "RM_UI_Title", "真实代谢",
    "RM_UI_ToggleHint", "按 N 打开代谢面板",
    "RM_UI_TabStatus", "状态",
    "RM_UI_TabTrend", "趋势",
    "RM_UI_TabHealth", "健康",
    "RM_Micro_sodium", "钠",
    "RM_Micro_potassium", "钾",
    "RM_Micro_calcium", "钙",
    "RM_Micro_iron", "铁",
    "RM_Micro_vitA", "维生素A",
    "RM_Micro_vitC", "维生素C",
    "RM_Micro_vitD", "维生素D",
    "RM_Micro_vitB1", "维生素B1",
    "RM_UI_Hydration", "水合",
    "RM_UI_Energy", "能量",
    "RM_UI_Load", "今日负荷",
    "RM_UI_Macros", "宏量",
    "RM_UI_Weight", "体重",
    "RM_Tier_Danger", "危险",
    "RM_Tier_Attention", "偏低",
    "RM_Tier_Ok", "达标",
    "RM_Tier_Excess", "过量",
    "RM_Hyd_Normal", "水合正常",
    "RM_Hyd_Thirsty", "口渴",
    "RM_Hyd_Low", "脱水",
    "RM_Hyd_Critical", "严重脱水",
    "RM_Ef_Normal", "精力充沛",
    "RM_Ef_Low", "能量偏低",
    "RM_Ef_Frozen", "力竭",
    "RM_UI_NoDisease", "暂无营养缺乏病",
    "RM_UI_Trend7", "近 7 天",
    "RM_NeatUI_Missing", "缺少前置 NeatUI：请订阅 Workshop 3508537032 后再使用真实代谢。",
}
